### ISSUE TITLE
Interview with students from Utrecht University

### ISSUE THREAD

**Issue by hbogner** [osm-cwg/tasks#13]
Sent to press:
"With a group of innovation sciences students from Utrecht University (the Netherlands) we are currently doing research on open data applications. We would very much like to interview you or one of your colleagues of the OSM Foundation this week if possible. 
Please let me know whether you are available. An interview can be done over the phone or skype for convenience."

Do we have somebody in the Netherlands?

**Comment by mvexel** [comment]
Stale, closing ('this week') happy to connect with NL contacts if still relevant.
