### ISSUE TITLE
Television programme enquiry

### ISSUE THREAD

**Issue by hbogner** [osm-cwg/tasks#15]
Mail sent to press@
"Hi,
I am developing a programme proposal for BBC Earth which is about mapping remote areas, and showing the reasons why it is so important, and hopefully showing the positive effects of mapping.
Would it be possible to chat to someone about our idea?  I would truly appreciate your thoughts on what we are hoping to do.  I’ve listed my contact details below and am available throughout today to chat.
Many thanks,
Helen "
@harry-wood is this something you could handle? I's BBC so ...

**Comment by harry-wood** [comment]
Yeah. I'll get in touch with her

**Comment by harry-wood** [comment]
Had a long chat with her, and then a follow up email. No reply to that yet
