### ISSUE TITLE
Next meeting

### ISSUE THREAD

**Issue by mvexel** [osm-cwg/tasks#16]
Planning here: http://doodle.com/gxzauewb7x6xkgu2

Please indicate availability by Sunday 4/29, thanks!

**Comment by mvexel** [comment]
Hmm that didn't go too well, only three participants, and I forgot to follow up in time. Apologies. I'll send out a new one for next week?

**Comment by harry-wood** [comment]
Sorry. I'm on holiday in New York at the moment, but when I'm back next week I'll be more available

**Comment by hbogner** [comment]
Out of date
