### ISSUE TITLE
a quick talk about satellite photography

### ISSUE THREAD

**Issue by hbogner** [osm-cwg/tasks#19]
Sent to press@ over a month ago:

"I write for The Verge, covering space and technology. I'm working on a piece about the business of satellite photography, and some of the complaints I've heard about existing players in the area. As a mapping project, I'm curious to hear your perspective on all this. For instance: Is Sentinel-2 making a big difference for you guys? I'd love to jump on the phone at some point this week to talk about it with someone from the project. I'm in New York, but I'm sure we could work out a time that would work for both zones. Let me know what you think makes sense here."

Would anyone like to respond?

**Comment by harry-wood** [comment]
look like we missed that one, back in June. Nobody replied? closing it now
