### ISSUE TITLE
create doodle for next meeting

### ISSUE THREAD

**Issue by mvexel** [osm-cwg/tasks#2]
We want a 30-60 minute meeting once a month. Set up a doodle to find a good time.

**Comment by hbogner** [comment]
Any news about this?

**Comment by mvexel** [comment]
We can do it at any time, and anyone can do it. Do you want me to?

On Mon, Mar 2, 2015 at 11:56 AM, hbogner <notifications@github.com> wrote:

> Any news about this?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/osm-cwg/tasks/issues/2#issuecomment-76780438>.
>



-- 
Martijn van Exel
skype: mvexel

**Comment by hbogner** [comment]
I know we are all busy, but we said once a month.
Should we stick to once a month, even if just for 15-30 minutes, to keep the rhythm?

**Comment by harry-wood** [comment]
OK. I'm not that keen on meetings, and I know @wonderchook & I are bit distracted by HOT election season, but I have gone ahead and created a doodle poll for a March CWG meeting:

http://doodle.com/35nfft7npvuyq3vk  <-- Fill in please

...with a random sprinkling of dates/times which suite me at least

**Comment by harry-wood** [comment]
Oopse. Looks like accidentally closed this task. That was silly.
It was also silly that I set-up a doodle at all really because "a bit distracted by HOT election" turned out to be a gross understatement. I'm still likely to be distracted by HOT stuff for the next couple of weeks
