### ISSUE TITLE
Louisiana newspaper usage of free map

### ISSUE THREAD

**Issue by hbogner** [osm-cwg/tasks#22]
Sent to press@ 4 days ago

"Hello, 
I am the editor at a small weekly newspaper in Louisiana. I would like to start using OpenStreetMaps for some visuals. I would prefer not to include a credit line under the graphic though. Is this acceptable? 
Thank you,
Quinn"

**Comment by harry-wood** [comment]
Closing this, as it was too long ago now. Don't think anyone replied to this
