### ISSUE TITLE
BBC News (Online) map request

### ISSUE THREAD

**Issue by hbogner** [osm-cwg/tasks#23]
Sent to press@ on 2015-10-20:

>Hi folks,
>My name’s ********* – I work for the BBC News (Online) team which covers the West of England.
>I am preparing a text piece for the website tomorrow (Weds), and would like to use an image taken from openstreetmap.org. I’ve read through the copyright, but just wanted to double-check all is ok.
>The image I’m referring to would be taken from this ‘tracker’ = http://z6z.co/river_severn_swim = and would be a zoomed in section of the River Severn similar to this…
>I am happy to add a credit to the image for ‘OpenStreetMap contributors’.
>Does that that sound ok with you?"
>Best wishes

**Comment by harry-wood** [comment]
I've replied (and copied in press@)
