### ISSUE TITLE
Use of OpenStreetMap

### ISSUE THREAD

**Issue by hbogner** [osm-cwg/tasks#24]
Sent to press@ today

"Hi,
We are investigating using your mapping system for a potential project.
But I have a couple of questions:

1. Can the maps work offline on a Windows Desktop?
2. Is there an API?
3. Can the maps be linked to a database for post code search?
4. Can we overlay graphics and other information onto the maps?
5. Apart from crediting OpenStreetMap, is there anything else we need to do when using this service?

Many thanks,
Darryl"

**Comment by harry-wood** [comment]
thanks for replying to that one @simonpoole
