### ISSUE TITLE
See if we can automatically create tasks from incoming email to press@

### ISSUE THREAD

**Issue by mvexel** [osm-cwg/tasks#8]
It would be great if press@ email would automatically appear as tasks in github so we can assign folks to act on them. This can be done with IFTTT: https://ifttt.com/github

**Comment by harry-wood** [comment]
We get a fair amount of spam email there though

**Comment by chrisfleming** [comment]
Yes, I was going to ask about how we deal with email to press@ - Ideally we need to "process" for making sure that at the very least real people get replies.

**Comment by hbogner** [comment]
I wondered what you meant with "fair amount of spam", because I got 2-3 mails for press@, and then I opened the spam folder and found it.
As Chris said we should have some kind of process for all those sent by real people, and with normal content.

**Comment by mvexel** [comment]
OK then we should give this github link a try, I say. I will set it up. Emails will still also go to the distro list so nothing is lost, but each email will also become a github issue so we can easily discuss and assign.

**Comment by mvexel** [comment]
Created recipe. I will monitor if it works and send ONE test email to press to confirm. (If it doesn't work, there may be a few more test emails...)
